services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data  
    restart: unless-stopped 
    
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped 

volumes:
  pgdata: